[phases.setup]
aptPkgs = ["python3", "python3-pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python scripts/migrate.py init"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"